export const foodWinePairings: Record<string, string[]> = {
    steak: ['Cabernet Sauvignon', 'Malbec', 'Syrah', 'Bordeaux'],
    beef: ['Cabernet Sauvignon', 'Malbec', 'Syrah'],
    burger: ['Zinfandel', 'Malbec', 'Cabernet Sauvignon'],
    salmon: ['Pinot Noir', 'Chardonnay', 'Sauvignon Blanc'],
    fish: ['Pinot Grigio', 'Sauvignon Blanc', 'Chardonnay'],
    tuna: ['Pinot Noir', 'Chardonnay'],
    shrimp: ['Sauvignon Blanc', 'Pinot Grigio', 'Champagne'],
    lobster: ['Chardonnay', 'Champagne', 'White Burgundy'],
    chicken: ['Chardonnay', 'Pinot Noir', 'Sauvignon Blanc'],
    duck: ['Pinot Noir', 'Syrah', 'Zinfandel'],
    pork: ['Pinot Noir', 'Riesling', 'Chardonnay'],
    lamb: ['Cabernet Sauvignon', 'Syrah', 'Bordeaux'],
    pasta: ['Chianti', 'Sangiovese', 'Pinot Grigio'],
    pizza: ['Chianti', 'Sangiovese', 'Barbera'],
    cheese: ['Chardonnay', 'Pinot Noir', 'Riesling', 'Port'],
    sushi: ['Riesling', 'Champagne', 'Sauvignon Blanc', 'Sake'],
    curry: ['Riesling', 'Gewürztraminer', 'Chenin Blanc'],
    spicy: ['Riesling', 'Gewürztraminer', 'Prosecco'],
    chocolate: ['Port', 'Cabernet Sauvignon', 'Zinfandel'],
    dessert: ['Moscato', 'Port', 'Riesling', 'Sauternes'],
    salad: ['Sauvignon Blanc', 'Pinot Grigio', 'Rosé'],
    vegetables: ['Sauvignon Blanc', 'Pinot Grigio', 'Rosé'],
  };
  
  export const wineDescriptions: Record<string, string> = {
    'Cabernet Sauvignon': 'Full-bodied red with bold tannins, black currant, and oak',
    'Pinot Noir': 'Light to medium-bodied red with red fruit, earthy, and silky',
    'Malbec': 'Medium to full-bodied red with dark fruit and smooth finish',
    'Syrah': 'Full-bodied red with dark fruit, pepper, and smoky notes',
    'Chardonnay': 'Full-bodied white with apple, butter, and vanilla notes',
    'Sauvignon Blanc': 'Crisp white with citrus, grass, and mineral notes',
    'Pinot Grigio': 'Light white with citrus and floral notes',
    'Riesling': 'Aromatic white with apple, honey, and floral notes',
    'Zinfandel': 'Bold red with jammy fruit and spice',
    'Champagne': 'Sparkling with citrus, toast, and elegance',
    'Chianti': 'Medium-bodied red with cherry, herb, and earth',
    'Sangiovese': 'Medium-bodied red with cherry and savory notes',
    'Bordeaux': 'Full-bodied red blend with structure and complexity',
    'Gewürztraminer': 'Aromatic white with lychee, rose, and spice',
    'Moscato': 'Sweet white with peach and floral notes',
    'Port': 'Fortified sweet wine with dark fruit and chocolate',
    'Rosé': 'Light pink wine with red fruit and refreshing acidity',
    'Prosecco': 'Sparkling white with apple and pear notes',
    'Sake': 'Japanese rice wine with clean, subtle flavors',
    'Sauternes': 'Sweet white with honey, apricot, and botrytis',
    'Barbera': 'Medium-bodied red with cherry and low tannins',
    'Chenin Blanc': 'Versatile white with apple, honey, and floral notes',
    'White Burgundy': 'Premium Chardonnay with mineral and oak complexity',
  };
  