model:
  name: wine_recognition_model
  version: 1.0
  input_shape: [224, 224, 3]
  num_classes: 100
  preprocessing:
    - type: resize
      target_size: [224, 224]
    - type: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  architecture:
    type: convolutional
    layers:
      - type: conv2d
        filters: 32
        kernel_size: 3
        activation: relu
      - type: maxpool
        pool_size: 2
      - type: conv2d
        filters: 64
        kernel_size: 3
        activation: relu
      - type: maxpool
        pool_size: 2
      - type: flatten
      - type: dense
        units: 128
        activation: relu
      - type: dense
        units: num_classes
        activation: softmax
  training:
    epochs: 50
    batch_size: 32
    learning_rate: 0.001
    optimizer: adam
  evaluation:
    metrics:
      - accuracy
      - precision
      - recall
      - f1_score